# Generated by Django 2.0.5 on 2018-05-05 02:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.CharField(default='934701945@qq.com', max_length=20, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_leg',
            field=models.IntegerField(default=0),
        ),
    ]
