# Generated by Django 2.0.5 on 2018-05-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180505_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.CharField(max_length=20, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_paw',
            field=models.CharField(max_length=50, verbose_name='密码'),
        ),
    ]
