# Generated by Django 2.0.5 on 2018-05-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180516_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_paw',
            field=models.CharField(max_length=80, verbose_name='密码'),
        ),
    ]
