# Generated by Django 2.0.5 on 2018-05-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180516_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=True, max_length=20, verbose_name='账号'),
        ),
    ]
